### ISSUE TITLE
`touch-action:none` prevents scrolling on some mobile devices

### ISSUE THREAD

**Issue by bryanbraun** [hammerjs/hammer-time#12]
I am running into issues where I am unable to scroll on some devices when dragging my finger on elements that are affected by `touch-action:none;`

I confirmed this wasn't an event-collision issue by testing this on the hammer-time index.html page: when placing `touch-action:none;` on the body element, I am unable to scroll the page.

Confirmed Affected devices:
- Google Nexus 6 running Android 5.0 (Chrome)
- Moto E running Android 4.4 (Chrome)

**Comment by bryanbraun** [comment]
This problem happens on browsers where touch-action is supported... meaning, the hammer-time polyfill isn't causing it. **It's just `touch-action:none;` working "as expected"**.

Looking at the specs for this property, it's understandable that scrolling is disabled:
- https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action
- http://www.w3.org/TR/pointerevents/#the-touch-action-css-property

This makes me wonder, is it a good idea to use hammer-time as a polyfill for `touch-action: none;`? I'm not using hammer-time in a desire to disable scrolling (or any other default behaviors). I just want to eliminate the 300ms delay (which hammer time does a pretty good job at).

**Comment by arschmitz** [comment]
@bryanbraun touch action is the built in standards way browsers allow you to remove the 300ms delay. Hammer time polyfills the relevant parts of the css property to make it so you can use this in all browsers today. As a polyfill we hope that hammer time wont be necessary in the future :-).

The fact that touch-action affects scrolling is necessary and intentional for this to cover cases of things like double tap to zoom, double tap to scroll ( many people don't know about this in ios ) and to allow better control over what events are emitted in a performant way. 

Im going to close this since this is the intentional behivor
